version: '3.8'

services:
  jenkins:
    image: custom-jenkins:latest
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - JENKINS_OPTS=--prefix=/jenkins
    depends_on:
      - dind
    networks:
      - jenkins_network

  dind:
    image: docker:19.03-dind
    container_name: dind
    privileged: true
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
    ports:
      - "2375:2375"
    volumes:
      - dind_storage:/var/lib/docker
    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local
  dind_storage:
    driver: local

networks:
  jenkins_network:
    external:
      name: project2-compose_jenkins_network  # 指定已有的外部网络
