version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # 允许 Jenkins 容器访问主机的 Docker 守护进程
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jenkins_network

  dind:
    image: docker:19.03-dind
    container_name: dind
    privileged: true # 允许 Docker 在 Docker 中运行
    volumes:
      - dind_storage:/var/lib/docker
    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local
  dind_storage:
    driver: local

networks:
  jenkins_network:
    driver: bridge
