version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://dind:2375  # 让 Jenkins 使用 dind 容器的 Docker 守护进程
      - JENKINS_OPTS=--prefix=/jenkins
    depends_on:
      - dind
    networks:
      - jenkins_network

  dind:
    image: docker:19.03-dind
    container_name: dind
    privileged: true
    command: --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock  # 启用非 TLS 的 2375 端口
    ports:
      - "2375:2375"  # 暴露 Docker 守护进程端口，供 Jenkins 使用
    volumes:
      - dind_storage:/var/lib/docker  # 持久化 Docker 数据
    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local
  dind_storage:
    driver: local

networks:
  jenkins_network:
    driver: bridge
