version: '3.8'

services:
  jenkins:
    image: custom-jenkins:latest
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - JENKINS_OPTS=--prefix=/jenkins
    depends_on:
      - dind
    networks:
      - project2-compose_project_network  # 确保网络名称正确

  dind:
    image: docker:19.03-dind
    container_name: dind
    privileged: true
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
    ports:
      - "2375:2375"
    volumes:
      - dind_storage:/var/lib/docker
    networks:
      - project2-compose_project_network  # 确保网络名称正确

volumes:
  jenkins_home:
    driver: local
  dind_storage:
    driver: local

networks:
  project2-compose_project_network:
    external: true  # 指定为外部网络，防止 Docker 自动生成
