version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts  # Use the official Jenkins LTS image
    container_name: jenkins
    privileged: true  # Required to execute Docker commands inside the container
    user: root  # Run as root user to facilitate Docker client installation
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Disable Jenkins setup wizard (optional)
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent storage for Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for communication with the host
    ports:
      - "8090:8080"  # Port for Jenkins Web UI
      - "50000:50000"  # Port for Jenkins agent communication
    networks:
      - jenkins_network

  dind:
    image: docker:20.10.24-dind  # Use Docker-in-Docker image
    container_name: dind
    privileged: true  # Required to run Docker-in-Docker
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS certificate directory
    volumes:
      - dind_storage:/var/lib/docker  # Persistent storage for Docker data
    ports:
      - "2376:2376"  # Port for Docker daemon (DinD)
    networks:
      - jenkins_network

networks:
  jenkins_network:  # Custom network to ensure communication between Jenkins and DinD containers

volumes:
  jenkins_home:  # Persistent volume for Jenkins data
  dind_storage:  # Persistent volume for Docker data (DinD)
