version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true  # Required to allow Jenkins to run Docker commands inside the container
    user: root  # Run as root user for permissions to access Docker
    environment:
      - DOCKER_HOST=tcp://dind:2376  # Set Docker host to communicate with the DinD service
      - DOCKER_CERT_PATH=/certs/client  # Path to Docker certificates
      - DOCKER_TLS_VERIFY=0  # Disable TLS verification for communication
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for communication with the host
      - /certs/client:/certs/client:ro  # Mount certificates directory for Docker client
    ports:
      - "8090:8080"  # Port for Jenkins Web UI
      - "50000:50000"  # Port for Jenkins agent communication
    networks:
      - jenkins_network
    depends_on:
      - dind  # Ensure that DinD service is started before Jenkins

  dind:
    image: docker:20.10.24-dind
    container_name: dind
    privileged: true  # Required for Docker-in-Docker functionality
    environment:
      - DOCKER_TLS_CERTDIR=/certs  # Enable TLS directory for Docker certificates
    volumes:
      - dind_storage:/var/lib/docker  # Persist Docker data for DinD
      - /certs/client  # Mount certificates directory
    ports:
      - "2376:2376"  # Port for Docker daemon communication
    networks:
      - jenkins_network

networks:
  jenkins_network:  # Custom network for communication between Jenkins and DinD

volumes:
  jenkins_home:  # Jenkins data volume
  dind_storage:  # DinD data volume
