version: '3.8'

services:
  jenkins:
    image: jenkinsci/blueocean  # 使用带有 Docker 客户端的 Jenkins 镜像
    container_name: jenkins
    privileged: true  # 需要特权模式才能正确运行 docker 命令
    user: root
    environment:
      - DOCKER_HOST=tcp://dind:2376  # 指定 Docker 守护进程的地址
      - DOCKER_TLS_VERIFY=0          # 禁用 TLS 验证
    volumes:
      - jenkins_home:/var/jenkins_home  # 持久化 Jenkins 数据
      - /var/run/docker.sock:/var/run/docker.sock  # 挂载 Docker socket，直接与宿主机通信
    ports:
      - "8090:8080"  # Jenkins Web UI 端口
      - "50000:50000"  # Jenkins 代理端口
    networks:
      - jenkins_network
    depends_on:
      - dind  # 确保 dind 服务先启动

  dind:
    image: docker:20.10.24-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=  # 禁用 TLS 目录，这样可以避免自动生成证书
    volumes:
      - dind_storage:/var/lib/docker  # 持久化 Docker 数据
    ports:
      - "2376:2376"  # Docker 守护进程的端口
    networks:
      - jenkins_network

networks:
  jenkins_network:  # 自定义网络，确保容器间通信

volumes:
  jenkins_home:  # Jenkins 持久化数据卷
  dind_storage:  # Docker 持久化数据卷（DinD）
